# Uncomment the 'shield: nice_view' lines below if you are using nice!view displays.
# Additionally, you should enable the display feature in 'config/blecorne.conf'.
---
include:
  - board: blecorne_left
    shield: nice_view
  - board: blecorne_right
    shield: nice_view

  # Build a "settings reset" firmware to clear persistent settings
  # (bluetooth connections, ZMK Studio keymap overrides, etc).
  - board: blecorne_left
    shield: settings_reset

  - board: blecorne_right
    shield: settings_reset
