name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"
      - "assets/**"
      - "gallery/**"
      - "README.md"
      - ".github/workflows/pages.yml"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
